sudo: required
dist: trusty
language: node_js
node_js:
- node
before_script:
- npm install
script:
- npm test
deploy:
  app: dolan-bio
  provider: heroku
  api_key:
    secure: hosaMvHRPfcFAsAOq0FhBHe/d8O6WzShjEmRvfuHyD+Ndi9OidMUEEl0ToyOt6rcxEt1lI0hZk7KCknXaI4CnUq30/RvMhh0mh6aDQMG1R0OVnDTMJHnYCb7bkdrPQtNdFT7O6scqTML8YJPV1Ksg+NyHOAOAb6vxQOAQ0hT5imu3u9FgNQkBq39A1PsXCh7ztj67x+pGmLNDJ08xIPhPACvns9J8c+Rg9SKOJtKTp38OStdpurPL94Rw7qR7tIroaX2Lt9RI0UQkbx382uU85uy4h4F2NNuRApk6vGNF8Aubvaf1bG8TtvWFKy2Wh9Cu/cf6ZxUxI6LxUH1Ih9CRiWAbFiR+nPWFJf9zX8KbVl3GaZoEugOJyH39QKtrMufBYQMzA/X060zw6PfYS6tansrCNVuHpNnD8qarSgmIhDFwksjfu4yHLH8oY/Y8VWF4eMBiDfsLoCiGgnupqR98OSkQfx0ytPnJ69vutK/Zq4yDMohcZGqSlgsSi9srqrlrLZF9PDQRznoQOrkQGf0gIId6Tem5WgQz4I4/pdZ90d03/QkjlOCAQBYhmgn6/Mt3bPKgdpdqCYC6a9NfWO2L69bBvvpHB0VDq/3T7nsAZe3+HGOFaiQOmM5dadWanQTBa2pzrs4p5EBceuLHVcreJreTXz0maXlqoqFevBVfWc=
